apiVersion: v1
kind: Service
metadata:
    name: shopping-nodeport
    namespace: shopping-app
spec:
    type: NodePort 
    selector:
        app: shopping 
    ports:
    - name: http
      port: 8080
      targetPort: 5000
      nodePort: 30080
