apiVersion: v1
kind: Service
metadata:
    name: shopping-cluster-ip
    namespace: shopping-app
spec:
    type: ClusterIP
    selector:
        app: shopping 
    ports:
    - name: http
      port: 8080
      targetPort: 5000
      protocol: TCP
