apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shopping
  name: demoliveness 
  namespace: shopping-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shopping
  template:
    metadata:
      labels:
        app: shopping
    spec:
      containers:
      - image: manningkubernetes/unhealthy:2.0
        name: demoliveness-container 
        livenessProbe: 
          httpGet:
            path: /
            port: 5000 
status: {}
